[project]
name = "dsllm"
version = "0.1.0"
description = "learning data science with LLMs"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "mccole>=4.0.0",
    "ruff>=0.15.12",
    "taskipy>=1.14.1",
]

[tool.taskipy.tasks.bib]
help = "Check bibliography entries."
cmd = "mccole bib"

[tool.taskipy.tasks.clean]
help = "Clean up generated and cache files."
cmd = """
    find . -type f -name '*~' -exec rm {} \\;
    find . -type d -name __pycache__ | xargs rm -rf
    find . -type d -name .ruff_cache | xargs rm -rf
"""

[tool.taskipy.tasks.check]
help = "Check code and project."
cmd = """
    mccole check --src . --dst docs
    typos *.md */*.md
"""

[tool.taskipy.tasks.serve]
help = "Serve generated HTML."
cmd = "python -m http.server -d docs"

[tool.taskipy.tasks.site]
help = "Build HTML."
cmd = """
    mccole build --src . --dst docs
    touch docs/.nojekyll
"""

[tool.mccole]
brand = "DSLLM"
skips = [
    "**/*~",
    "**/__pycache__/**",
    "docs/**",
    "log/**",
    "uv.lock",
    "*.csv",
    "*.db",
    "*.py",
    "*.sh"
]
